### ISSUE TITLE
moveToEnd() is not working correctly when a grouping field is used

### ISSUE THREAD

**Issue by giovanniledda** [spatie/eloquent-sortable#103]
Hi,
Here the scenario: I've a "sortable" Page model that is related to a Topic model (foreign_key: topic_id) and "sort_when_creating" is true. 
The sort order for each group of Pages is related to the Topic: if Topic 1 has five pages they have order_column values of 1,2,3,4,5, if I've a "Topic 2" with four pages, order_column's values are "1,2,3,4".

Here is the bug: if I create the first Page for the Topic 1, is "topic_id" is null, so the order_column value is 1. Then I associate the Page to the Topic and I call the moveToEnd() (topic_id now is 1): order_colum is 1, because I've just one Page. 
Then I create a second Page:  "topic_id" is null, so the order_column value is 1, again..when I associate the Page to the Topic 1 and I call the moveToEnd(), I'm expecting the order_column value to be "2"...but is not: its value is still 1.

I've already forked the project and solved the bug (I ran the tests and they are green), I'm opening the issue just to associate the PR to it...I'm not sure if I'm doing right....sorry, in case!

Thanks

**Comment by freekmurze** [comment]
Well continue the conversations in #104
