### ISSUE TITLE
Not firing model events when changing order

### ISSUE THREAD

**Issue by colinmackinlay** [spatie/eloquent-sortable#118]
Perhaps a feature request rather than an issue. 

When I sort a model and change its order column I would like it recognise that is has been updated in the same way as if I changed any other field. As well as changing the `updated_at` column (which it does) I need to use `$touches` to touch the parent and also to fire the `updated` event so that I can mark the "parent of the parent" as updated.  These don't appear to happen.

**Comment by colinmackinlay** [comment]
Would be good if @freekmurze could take a quick look to see if this can be fixed. Although there were no other comments there were two thumbs up from @hurycz and @morphsteve which indicates some agreement that it's a "thing"! Thanks for looking

**Comment by freekmurze** [comment]
I currently don't have time to spend on this, but feel free to create a PR with tests and updated docs. if the code is simple, I'll consider merging it.
