### ISSUE TITLE
Order is getting overwritten when creating

### ISSUE THREAD

**Issue by phh** [spatie/eloquent-sortable#119]
Example in tinker:
`MyModel::create(['sort_order' => 15])` results in the `sort_order` being 1.

I was expecting the `sort_order` to be 15, but I wonder if this is the expected behavior?

Currently solved by adding this to my model:

```php
public function shouldSortWhenCreating(): bool
{
    if (!is_null($this->{$this->determineOrderColumnName()})) {
        return false;
    }

    return $this->sortable['sort_when_creating'] ?? config('eloquent-sortable.sort_when_creating', true);
}
```

**Comment by phh** [comment]
This could be fixed like this or by adding another config like:

```php
public function shouldSortWhenCreating(): bool
{
    if (!is_null($this->{$this->determineOrderColumnName()}) && ! $this->sortable['overwrite_sort_when_creating'] ?? ! config('eloquent-sortable.overwrite_sort_when_creating', true);) {
        return false;
    }

    return $this->sortable['sort_when_creating'] ?? config('eloquent-sortable.sort_when_creating', true);
}
```

Not tested or formatted, just the basic idea.

**Comment by jrean** [comment]
@phh
Or:
- Don't add the `sortable` property to your model
- Publish the package config and keep `eloquent-sortable.sort_when_creating` to `true`
- When you need to disable the automatic sorting add:
```
config(['eloquent-sortable.sort_when_creating' => false]);
// your code
config(['eloquent-sortable.sort_when_creating' => true]);
```
