### ISSUE TITLE
moveOrderUp select always first element

### ISSUE THREAD

**Issue by zoomyboy** [spatie/eloquent-sortable#13]
In the method 'moveOrderUp' of the trait, it selects the first element of all the ones with lower ordering than the current:

```
$swapWithModel = static::limit(1)
->ordered()
->where($orderColumnName, '<', $this->$orderColumnName)
->first();
```

Shouldn't that be 'last()' in line 131, because the last element would be the element 'above' the current one, since the first is always the one with order number 1?

**Comment by freekmurze** [comment]
Thanks for letting me know. If fixed this bug in  the newly tagged v2.1.1
