### ISSUE TITLE
有一种情况下， 调用 moveOrderUp 上移操作可能会不准确。

### ISSUE THREAD

**Issue by gyp719** [spatie/eloquent-sortable#158]
如： 数据表中 有一个 status 字段 0-未上线 1-上线 2-下线

此时创建， order 字段增长， 但我有3个tab栏 来显示 对应的 3种状态的列表。

在 status=1 上线列表进行， moveOrderUp 上移操作， 虽然 order 字段会变化， 但可能依旧 小于 上线列表的 order 字段值， 因为有其他状态类型的列表干扰到了，可能说的不是很清楚。

![image](https://github.com/spatie/eloquent-sortable/assets/30563368/15787481-3cfe-4fb0-bfce-f850fc545efa)

**Comment by freekmurze** [comment]
I don't understand your language.

**Comment by hsk-story** [comment]
Override the buildSortQuery method in the Model and add a query condition for the status field in the query object.
