### ISSUE TITLE
moveOrderStart() and moveOrderEnd()

### ISSUE THREAD

**Issue by furzewolf** [spatie/eloquent-sortable#16]
I propose adding two new methods, `moveOrderStart()` and `moveOrderEnd()`. These methods would swap the model with the very first one, or the very last one, respectively.

I achieved the creation of these methods simply by getting `moveOrderUp()` and `moveOrderDown()` and swapping the order type (replacing `ordered()` with `ordered('desc')` in `moveOrderEnd()` and removing the `'desc'` in `moveOrderStart()`).

**Comment by freekmurze** [comment]
I'd accept a PR that adds `moveToStart()` and `moveToEnd()` to the package. These functions would not swap content but simply move an item first. 

I'd also accept a `swapOrder` function that accepts to models and swaps the order.

**Comment by driade** [comment]
pull request #22 should help with the first part

**Comment by driade** [comment]
Pull request #23 should help with the second part

**Comment by freekmurze** [comment]
Implemented in `v2.2.0`. Thanks for those PRs @driade 👍
