### ISSUE TITLE
is_array check in SortableTrait::setNewOrder

### ISSUE THREAD

**Issue by unstoppablecarl** [spatie/eloquent-sortable#17]
https://github.com/spatie/eloquent-sortable/blob/master/src/SortableTrait.php#L52

Is there a reason to use `is_array()` instead of type hinting the argument like bellow?

```php
public static function setNewOrder(array $ids, $startOrder = 1){ /* ... */ }

```

Changing this would also remove the only use of `SortableException`.

**Comment by freekmurze** [comment]
You' re right that this check should better be a typehint. Unfortunately changing the signature of an function in an interface is a breaking change.

I'll fix this is the next major version of the package.

**Comment by unstoppablecarl** [comment]
That is what I thought. I wanted to make sure I was not missing something. Thanks for the response.
