### ISSUE TITLE
Add at position

### ISSUE THREAD

**Issue by lukasoppermann** [spatie/eloquent-sortable#18]
What do you think about setting a desired order value when for a new model?

```php
$model->setOrder(3);
```

This should place the given model at position 3 and move current models 3-X one up.

**Comment by freekmurze** [comment]
Mmm, not a fan of this as the `order_column` may contains gaps (for example after deleting records).  If you need this, do it in your own project.

**Comment by lukasoppermann** [comment]
Ohh. 😦 I would have thought that the package deals with deleting records and fixed gabs in the `order_column`.

Also, I don't really see how a gap in the `order_column` column would be a problem. You would just get all items with an `order_column` > `X` (where `X` is the number from `setOrder`) and set them all to `X+n` (where `n` is just an incrementing counter). This would also remove at least the gaps above `X`. 😄

**Comment by freekmurze** [comment]
Nope, I don't see those gaps as a problem, because we only use `order_column` to sort on. The meaning of a number itself in that column means nothing.

I know there could be some logic added to make what you're proposing work. But I'd like to keep this package lightweight. If there are more users asking for this, I'll reconsider. For now, if you want this, add it to your own project.

**Comment by lukasoppermann** [comment]
@freekmurze I do agree that gaps are not a real problem. However, its a little sad that there is no chance for a `setOrder` method. I think it would just be a very small addition and not bloat the package (I might be missing something though).

**Comment by freekmurze** [comment]
@lukasoppermann Know what? Whip up a PR with some tests that adds this to the package. If the code feels lightweight to me I'll pull it. If not, then you have some quality code for in your own project.

**Comment by danpalmieri** [comment]
It would be great!
