### ISSUE TITLE
PHP 8.4.1 Compatibility issue.

### ISSUE THREAD

**Issue by laze** [spatie/eloquent-sortable#183]
Deprecated: Spatie\EloquentSortable\SortableTrait::setNewOrder(): Implicitly marking parameter $primaryKeyColumn as nullable is deprecated, the explicit nullable type must be used instead in /var/www/html/vendor/spatie/eloquent-sortable/src/SortableTrait.php on line 44

The code should be like this, enabling the `null` attribute type not to use implicitly marking the parameter's value as `null`:
```
public static function setNewOrder(
        $ids,
        int $startOrder = 1,
        string|null $primaryKeyColumn = null,
        callable|null $modifyQuery = null
    ): void {
...
}
```

**Comment by kkpo4553** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the setNewOrder method signature in SortableTrait.php to explicitly declare nullable types for $primaryKeyColumn and $modifyQuery parameters, addressing the deprecation warning.

You can review changes in this commit: https://github.com/kkpo4553/spatie-eloquent-sortable-183/commit/70fcda4caac7a58c84c17874aee50949f5e18750.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by freekmurze** [comment]
We'd accept a PR that fixes this.

**Comment by freekmurze** [comment]
Fixed in the latest release.
