### ISSUE TITLE
Grouped ordering

### ISSUE THREAD

**Issue by nicolas-brousse** [spatie/eloquent-sortable#2]
Hi,

Is it possible to add a feature to permit grouped ordering?

**Comment by schmidex** [comment]
any update on this?

**Comment by freekmurze** [comment]
No sorry, haven't come around to this yet. If you need this functionality feel free to submit a PR.

**Comment by freekmurze** [comment]
Hi, due to time constraints it'll probably be very long until we add this ourselves. If you want this feature submit a PR.
