### ISSUE TITLE
Unable to run all the test with illuminate/support 5+

### ISSUE THREAD

**Issue by driade** [spatie/eloquent-sortable#21]
Hello, good night.

Maybe I am wrong but running the tests with the latest version of Illuminate is not possible, as the method "lists" was removed.

For example

`$newOrder = Collection::make(Dummy::all()->lists('id'))->shuffle()->toArray();`

I think the correct method on Illuminate 5 is "pluck".

Should we make SortableTest compatible with both?

**Comment by driade** [comment]
Note: 5.3+

**Comment by freekmurze** [comment]
Thanks for notifying me. I've fixed this in `dev-master` now.
