### ISSUE TITLE
Allow collections to be passed to setNewOrder

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/eloquent-sortable#27]
The method allow instances of `Illuminate\Support\Collection` besides plain arrays.

https://github.com/spatie/eloquent-sortable/blob/master/src/SortableTrait.php#L52

**Comment by freekmurze** [comment]
We'll accept a PR for this with tests.

**Comment by freekmurze** [comment]
Fixed in `2.3.0`. Thanks again @mpociot
