### ISSUE TITLE
Soft deleting models are not reordered as expected

### ISSUE THREAD

**Issue by sebdesign** [spatie/eloquent-sortable#31]
I have a model which uses the `SoftDeletes trait` and the `SortableTrait`. On the front-end of my app I'm displaying only the ordered non-trashed models, but on the back-end I'm including the trashed models, which can be reordered.

The soft deleting trait adds a constraint when the `setNewOrder` method is looping over the ids, therefore the order column is updated only on the non-trashed models. This is a bug because the new order is not synced across all the given models, which gives us duplicate order numbers, and that leads to unexpected results.

I'm happy to submit a PR if this is something that should be fixed. Thanks!

**Comment by freekmurze** [comment]
I'd accept a PR that can fix this is an a simple way.
