### ISSUE TITLE
Question re: sort_when_creating

### ISSUE THREAD

**Issue by mkarnicki** [spatie/eloquent-sortable#41]
Hi Freek/Spatie,

I'm looking into using your packages. I found this one and was reading the docs. GitHub says:

> If you don't set a value $sortable['sort_when_creating'] the package will automatically assign the highest order number to a new model;

I don't fully understand the opposite case, maybe it's one of those "too obvious" things haha. What happens when I DO set that value (as shown above)? What does `sort_when_creating = true` mean?

Thanks!

**Comment by freekmurze** [comment]
If you don't set `sort_when_creating` or when it has been set and it is true, the package will automatically fill the `order_column` of your model with a highest order number.

If you set `sort_when_creating` to false the package won't fill `order_column`.

**Comment by mkarnicki** [comment]
I see, thank you for your explanation, Freek! :1st_place_medal:
