### ISSUE TITLE
Is there the functional for increment sorting field value by tens ?

### ISSUE THREAD

**Issue by gallyamow** [spatie/eloquent-sortable#42]
I need to the values should be series of 10, 20, 30 ... etc

**Comment by freekmurze** [comment]
The package works best if you let it take core of the values in the sorting field. If you need those values to be something else than incremental numbers, than it's better to roll your own solution.

**Comment by Omranic** [comment]
I was looking into this today as we need it, maybe I can send PR. Are you willing to accept it if it's BC?

**Comment by freekmurze** [comment]
If the code is easy to understand, easily configurable, non-breaking and fully tested I'd considering accepting a PR 😄
