### ISSUE TITLE
Rearranging Isn't Working

### ISSUE THREAD

**Issue by cvassios-ekko** [spatie/eloquent-sortable#52]
I'm using eloquent-sortable in my Laravel Admin CRUD table and everything is appearing okay, but when I try to reorder items, I get a success message but the items don't reorder.

I wasn't able to find any guidelines on how the database tables should be set up, so I'm wondering if my `order_column` isn't set up correctly.

**Video Controller**
```
use SortableTrait;

public $sortable = [
    'order_column_name' => 'order',
    'sort_when_creating' => true,
];
...
$grid->order('Order')->orderable()->sortable();
```
**Database**
The database has a column `order` with integers, but they aren't unique. Hoping they don't NEED to be because it would be a pain to fix this.

**Comment by freekmurze** [comment]
How are you reordering items?

**Comment by cvassios-ekko** [comment]
I'm not sure I understand your question. I'm using this repo to do drag and drop
![screen shot 2017-10-17 at 3 07 34 pm](https://user-images.githubusercontent.com/31114329/31692089-3afd9886-b34d-11e7-88ef-6218b4128fc6.png)

**Comment by freekmurze** [comment]
What info is sent to the server?

**Comment by cvassios-ekko** [comment]
The column "order" in my database

**Comment by freekmurze** [comment]
What code do you use to update the order? What data is passed to that code?

**Comment by cvassios-ekko** [comment]
I'm showing all the code I have related to this. I just followed what I could use from the README instructions. Where can I find an example of code I can use to update and pass data?

**Comment by freekmurze** [comment]
There's an example in the readme:

```php
/**
 * the record for model id 3 will have record_column value 1
 * the record for model id 1 will have record_column value 2
 * the record for model id 2 will have record_column value 3
 */
MyModel::setNewOrder([3,1,2]);
```

Make sure you pass the right values to `setNewOrder`.

**Comment by cvassios-ekko** [comment]
So if I have a hundred or more items, my setNewOrder would have to be an array of all those items?

And if I want to move an item up or down multiple times I'd need a different setNewOrder for each move?

**Comment by freekmurze** [comment]
> So if I have a hundred or more items, my setNewOrder would have to be an array of all those items?

It would have to be an array with the ids of those items.

> And if I want to move an item up or down multiple times I'd need a different setNewOrder for each move?

Yes
