### ISSUE TITLE
How I can make it order by type (grouped)

### ISSUE THREAD

**Issue by vedmant** [spatie/eloquent-sortable#54]
Hi, I have have a model with multiple types (just a filed "type") and each type should have it's own order, how I can achieve this with this package? If no, can you recommend any alternative?

**Comment by freekmurze** [comment]
Override the `setHighestOrderNumber` function in your own model. Add logic there do determine the highest number for the records of a type.

**Comment by Mul-tiMedia** [comment]
@vedmant checkout my fork of this package.
https://github.com/Mul-tiMedia/eloquent-sortable

**Comment by gauravmak** [comment]
Or you may override `buildSortQuery()` method in your model and add an additional where condition to the query so that all of the sorting related operations respect the grouping.
