### ISSUE TITLE
Add Global Scope

### ISSUE THREAD

**Issue by IsraelOrtuno** [spatie/eloquent-sortable#61]
I have seen in other issues that you pretend to keep this package as light as possible, but I think adding a global scope to order by the `order` column by default would make sense for this package. Would you consider a PR for this?

**Comment by freekmurze** [comment]
The package already has a scope called `scopeOrdered`.

**Comment by Rogierownage** [comment]
Just to clarify since i was trying to do this myself and got here, this is an example of how you can register the global scope. Add this to your model.

(I can't get the formatting right but you get the picture)

/**
     * The "booting" method of the model.
     */
    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope('ordered', function (Builder $query) {
            $query->ordered();
        });
    }
