### ISSUE TITLE
Reset order when destroy

### ISSUE THREAD

**Issue by Albvadi** [spatie/eloquent-sortable#67]
Hi,
after all thanks for the package, it´s super usefull!

One question about destroy models. Is there no method to reset the positions?
For example, I have the following models:
```php
[
  0 => [
    "title" => "Item 1",
    "order_column" => "1",
  ],
  1 => [
    "title" => "Item 1",
    "order_column" => "2",
  ],
  2 => [
    "title" => "Item 1",
    "order_column" => "3",
  ],
  3 => [
    "title" => "Item 1",
    "order_column" => "4",
  ],
]
```

Now, if I destroy Item 3, there are a gap between orders 2 and 4. 
A method that reset all orders without gap??

Actually, I do this, but I´m not sure if it´s the best option:
```php
public function destroy( Link $link )
{
    $link->delete();

    $orderedLinks = Link::ordered()->pluck('id')->toArray();

    Link::setNewOrder($orderedLinks);

    return redirect()->back();
}
```

Thank you!!

**Comment by freekmurze** [comment]
No, there is no functionality to close the gaps, mostly because for most projects a gap isn't a big problem.

**Comment by carloshc** [comment]
Hi, 

> ```
> public function destroy( Link $link )
> {
>     $link->delete();
> 
>     $orderedLinks = Link::ordered()->pluck('id')->toArray();
> 
>     Link::setNewOrder($orderedLinks);
> 
>     return redirect()->back();
> }
> ```

Where did you put this method? 

Thank you.

**Comment by milewski** [comment]
for me adding this was enough to fix this issue:

```php
protected static function boot()
{
    parent::boot();

    static::deleted(function (Sortable $model) {

        static::setNewOrder($model->buildSortQuery()->pluck($model->primaryKey)->toArray());

    });
}
```

**Comment by jpmurray** [comment]
@milewski You should send a PR for this. I know Freek told it's not a problem for _most_ projects, but that still doesn't say all of them. It could be on a setting switch that's not enabled by default for example.

**Comment by clementmas** [comment]
Gaps make it harder to find the siblings.

I was about to PR an optional `sort_when_deleting` config option but then I saw that @freekmurze closed the same PR https://github.com/spatie/eloquent-sortable/pull/115. He doesn't want to maintain a feature he doesn't need which is fair.

So instead I converted my code into a Trait that can be copy/pasted into any project:

`app/Models/Traits/SortableOnDeleteTrait.php`
```php
<?php

namespace App\Models\Traits;

use Illuminate\Support\Facades\DB;

trait SortableOnDeleteTrait
{
    public static function bootSortableOnDeleteTrait()
    {
        static::deleted(fn (self $model) => $model->removeOrder());
    }

    public function removeOrder()
    {
        $orderColumnName = $this->determineOrderColumnName();
        $orderValue = $this->$orderColumnName;

        if (is_null($orderValue)) {
            return;
        }

        if (config('eloquent-sortable.ignore_timestamps', false)) {
            static::$ignoreTimestampsOn = array_values(array_merge(static::$ignoreTimestampsOn, [static::class]));
        }

        $this->buildSortQuery()
            ->where($orderColumnName, '>', $orderValue)
            ->update([$orderColumnName => DB::raw("`{$orderColumnName}` - 1")]);

        if (config('eloquent-sortable.ignore_timestamps', false)) {
            static::$ignoreTimestampsOn = array_values(array_diff(static::$ignoreTimestampsOn, [static::class]));
        }
    }
}
```

This query only updates the necessary records which is much more efficient than using `setNewOrder` for large datasets.
