### ISSUE TITLE
Relation

### ISSUE THREAD

**Issue by jrean** [spatie/eloquent-sortable#7]
Hi,
Very nice package!

I try to understand how can I use it for `pivot` tables?
I have a Venue and an Event model. A Venue can have many Event(s) and an Event belongToMany Venue(s). So I have the pivot table but no Eloquent Model...
For each Venue, I would like to display the attached Event(s) and being able to manage Event(s) order for that Venue. I should keep track of Event position within the pivot table, right?

Can you help me please?

**Comment by sebastiandedeyne** [comment]
Hi, sorry for the late reply.

In case it's still relevant, this should be possible by creating a model for your pivot table, e.g. VenueEvent, this model could then implement the sortable trait.
