### ISSUE TITLE
Why drop support for Laravel < 5.8?

### ISSUE THREAD

**Issue by ryrobbo** [spatie/eloquent-sortable#70]
Came across this great library you have put together but discovered I can't use as our application is on Laravel 5.5.

Going through your changelogs and commits, there doesn't seem to be a reason as to why you have dropped support for < 5.8 despite the code in src/ not changing for 2 years.

**Comment by freekmurze** [comment]
You can still use version 3.4.4.

**Comment by ryrobbo** [comment]
Thank you for pointing me to the right place.
