### ISSUE TITLE
laravel 5.4 with php5.6 can not install.

### ISSUE THREAD

**Issue by spencerchang** [spatie/eloquent-sortable#75]
The eloquent-sortable v2.3.0 is lastest version support php5.X but can not install in laravel 5.4 that is the lastest version support php 5.X.

Many old system need more time to upgrade to php 7.X.
Any possible to provide a version support laravel 5.4 with php5.X?

Thanks.

**Comment by freekmurze** [comment]
No, we don't need that ourselves, so it makes no sense for us to invest time in this. Feel free to fork our code.
