### ISSUE TITLE
Update order column & re-sort all models

### ISSUE THREAD

**Issue by dillingham** [spatie/eloquent-sortable#87]
If `$model->update(['order' => 3]);`..
Would be 🔥 if other models updated also.
So the model originally with `order` 3 would be 4 and so on.
I have the `order` in a nova field and it would make it so simple.
Not quite sure how one would go about it design wise though.

**Comment by freekmurze** [comment]
This strategy would probably not be efficient in large tables, so the package doesn’t do that.

If you want this behaviour, add it to your own project

**Comment by dillingham** [comment]
@freekmurze makes sense, thanks.

Here's my early attempt incase anyone else lands here:

```php
static::saved(function($model) {
    if($model->wasChanged('order')) {
        $ids = static::ordered()->pluck('id');
        static::setNewOrder($ids);
    }
});
```
I actually needed additional scope:

```php
static::saved(function($model) {
    if($model->wasChanged('order')) {
        $ids = static::where('group_id', $model->group_id)->ordered()->pluck('id');
        static::setNewOrder($ids);
    }
});
```

**Comment by bmoex** [comment]
As i noticed the comment for the attempt, i wanted to share my own implementation as i encountered this same problem. I created a portable support class in laravel for this. Feel free to use/abuse when needed.

**Usage:**
```php
$wantedOrder = 5;
$model = Model::create();
\App\Support\Sortable::set($wantedOrder, $model);
```

**Support Class:**
```php
<?php

namespace App\Support;

use Illuminate\Database\Eloquent\Model;

class Sortable
{
    public static function set(int $sequence, Model $model, string $field = 'order', int $step = 1): void
    {
        if ($model->getAttribute($field) === null) {
            throw new \LogicException('Model does not seem to have the configured field');
        }

        // Store id for usage in where not
        $modelId = $model->id;

        // Set sequence value for requested model
        $model->{$field} = $sequence;
        $model->save();

        // Now increment every other model until a gap is found with only 1 step
        $newSequence = $sequence + 1;
        $model::query()
            ->where($field, '>=', $sequence)
            ->whereNot('id', $modelId)
            ->orderBy($field)
            ->each(function (Model $model) use (&$newSequence, $field) {
                if ($model->{$field} > $newSequence) {
                    // If a sequence gap is found, abort looping as it's working as intended
                    return false;
                }

                $model->{$field} = $newSequence;
                $model->save();

                $newSequence++;

                return true;
            });

        // Now reset all model sequences for possible step setup
        self::reconfigure($model, $field, $step);
    }

    public static function reconfigure(Model $model, string $field = 'order', int $step = 1): void
    {
        $sequence = 0;
        $model::query()
            ->where($field, '>=', 0)
            ->orderBy($field)
            ->each(function (Model $model) use (&$sequence, $step, $field) {
                $sequence = $sequence + $step;
                $model->{$field} = $sequence;
                $model->save();
            });
    }
}
```

**Comment by lucasdcrk** [comment]
For anyone facing the same challenge, I share my implementation in my model's observer.
It checks whether the newly set order collides with another order attribute, if so it swaps the order of both.
If more there is more than one collision it re-orders everything.

// PostObserver.php
`public function updating(Post $post)
{
    if ($post->isDirty('order')) {
        $q = Post::query()
            ->where('id', '!=', $post->id)
            ->where('order', '=', $post->order);

        if ($q->count() > 1) {
            Post::setNewOrder($q->ordered()->pluck('id')->toArray());
        }

        $q->update([
            'order' => $post->getOriginal('order')
        ]);
    }
}`
