### ISSUE TITLE
Sorting without touching timestamps

### ISSUE THREAD

**Issue by danpalmieri** [spatie/eloquent-sortable#88]
Is there a way to sort without changing the updated_at column?

My model defaults is timestamps active BUT when sorting with `Model::setNewOrder()` I would like to disable it temporarily.

Any help is welcome.

**Comment by jonagoldman** [comment]
Sure, add this to your model:

```php
class MyModel extends Model
{

    // flag
    protected static $ignoreTimestamps = false;

    // setter
    public static function ignoreTimestamps(bool $ignore = true)
    {
        static::$ignoreTimestamps = $ignore;
    }

    // override the method in the HasAttributes trait to also check for the custom flag
    public function usesTimestamps()
    {
        return parent::usesTimestamps() && !static::$ignoreTimestamps;
    }

   // ...

}
```

And then to sort:

```php
// set flag
MyModel::ignoreTimestamps();

// sort
MyModel::setNewOrder($order);

// reset flag
MyModel::ignoreTimestamps(false);
```

The `$timestamps` property in the model is not static so you can't use that,
but Laravel always checks the `usesTimestamps()` method before setting the timestamps.

Hope it helps.

**Comment by danpalmieri** [comment]
@jonagoldman Thank you for answering in the light speed! **It worked like a charm!**

**Comment by lloricode** [comment]
this is nice,

it is possible this to include in package?

**Comment by lloricode** [comment]
> Sure, add this to your model:
> 
> ```
> class MyModel extends Model
> {
> 
>     // flag
>     protected static $ignoreTimestamps = false;
> 
>     // setter
>     public static function ignoreTimestamps(bool $ignore = true)
>     {
>         static::$ignoreTimestamps = $ignore;
>     }
> 
>     // override the method in the HasAttributes trait to also check for the custom flag
>     public function usesTimestamps()
>     {
>         return parent::usesTimestamps() && !static::$ignoreTimestamps;
>     }
> 
>    // ...
> 
> }
> ```
> 
> And then to sort:
> 
> ```
> // set flag
> MyModel::ignoreTimestamps();
> 
> // sort
> MyModel::setNewOrder($order);
> 
> // reset flag
> MyModel::ignoreTimestamps(false);
> ```
> 
> The `$timestamps` property in the model is not static so you can't use that,
> but Laravel always checks the `usesTimestamps()` method before setting the timestamps.
> 
> Hope it helps.

this is nice,

it is possible this to include in package?
