### ISSUE TITLE
Overwriting order on create

### ISSUE THREAD

**Issue by thijsdemaa** [spatie/eloquent-sortable#9]
When I provide the `order_column` value in the create method of the model, I would not like it to be overwritten. Could you make sure it checks if the `order_column` is present, and then not set the sort_order? Or make this optional

**Comment by freekmurze** [comment]
That makes sense. I'd accept a PR that adds this to the package.

**Comment by cdarken** [comment]
@thijsdemaa did you make a pull request for this? I can't find it.
